openapi: 3.0.0
info:
  title: 'sample api'
  version: 1.0.0
paths:
  /user:
    post:
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostUserRequest'
      responses:
        '200':
          description: 'OK'
        '500':
          description: 'Internal Server Error'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerError'
  /user/{id}:
    get:
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 'OK'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetUserResponse'
        '500':
           description: 'Internal Server Error'
           content:
             application/json:
               schema:
                 $ref: '#/components/schemas/ServerError'
    delete:
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 'OK'
        '500':
           description: 'Internal Server Error'
           content:
             application/json:
               schema:
                 $ref: '#/components/schemas/ServerError'
components:
  schemas:
    GetUserResponse:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
    PostUserRequest:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
    ServerError:
      type: object
      properties:
        status:
          type: number
        message:
          type: string
